"""
seed_demo_data.py — Seeds clean demo data for ATLAS presentation.

Creates:
  1. One strategy with full lifecycle trace (generated -> code -> backtest -> validated -> promoted -> deployed)
  2. One backtest_result with realistic metrics
  3. One open position (AAPL buy @ $100, current @ $105, unrealized PnL = +$50)
  4. One closed trade (completed buy->sell cycle, realized PnL = +$110)
  5. market_data_l1 entries for price evidence
"""
import asyncio
import asyncpg
import uuid
from datetime import datetime, timezone, timedelta

DB_URL = "postgresql://postgres:password@localhost:5433/atlas"

# Strategy IDs (fixed for reproducibility)
STRATEGY_ID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
TRACE_ID = "trace_demo_001"

async def seed(conn):
    now = datetime.now(timezone.utc)

    # =========================================================================
    # 1. STRATEGY with full lifecycle
    # =========================================================================
    print("[SEED] Creating strategy with full lifecycle...")

    await conn.execute("""
        INSERT INTO strategies (id, name, code, parameters, status, created_at, author_agent, trace_id)
        VALUES ($1, 'mean_reversion_enhanced_v3', $2, $3, 'active', $4, 'IdeatorAgent', $5)
    """, STRATEGY_ID,
       # Realistic strategy code
       """
import talib
import numpy as np

def execute(data):
    close = data['close']
    volume = data['volume']
    rsi = talib.RSI(close, timeperiod=14)
    sma_20 = talib.SMA(close, timeperiod=20)
    sma_50 = talib.SMA(close, timeperiod=50)
    vwap = data['vwap']

    conditions = []
    # Mean reversion: RSI < 30 (oversold) + price below vwap
    if rsi[-1] < 30 and close[-1] < vwap:
        conditions.append({'type': 'entry', 'side': 'long',
                          'confidence': 0.75, 'reason': 'oversold_rsi'})

    # Exit: RSI > 70 (overbought) or price > sma_20
    if rsi[-1] > 70 and close[-1] > sma_20[-1]:
        conditions.append({'type': 'exit', 'reason': 'overbought_rsi'})

    return {
        'signal': 'buy' if any(c['type'] == 'entry' for c in conditions) else 'neutral',
        'confidence': max((c.get('confidence', 0) for c in conditions), default=0.0),
        'conditions': conditions
    }
"""      .strip(),
       # Parameters
       '{"rsi_period": 14, "sma_short": 20, "sma_long": 50, "entry_threshold": 30, "exit_threshold": 70, "position_size_pct": 0.05, "stop_loss_pct": 0.05, "take_profit_pct": 0.10}', now, TRACE_ID)

    print("  [OK] Strategy created: mean_reversion_enhanced_v3")

    # =========================================================================
    # 2. BACKTEST RESULT
    # =========================================================================
    print("\n[SEED] Creating backtest result...")

    backtest_start = now - timedelta(days=90)
    backtest_end = now - timedelta(days=1)

    await conn.execute("""
        INSERT INTO backtest_results
            (strategy_id, start_date, end_date, sharpe, cagr, max_drawdown,
             win_rate, total_trades, passed_validation, entry_count, exit_count,
             bars_processed, short_window_score, score_7d, score_14d, score_30d)
        VALUES ($1, $2, $3, 1.85, 22.4, -8.3, 0.67, 142, TRUE, 145, 140,
                45000, 0.72, 0.68, 0.71, 0.74)
    """, STRATEGY_ID, backtest_start, backtest_end)

    print("  [OK] Backtest result: Sharpe=1.85 WinRate=67% Trades=142")

    # =========================================================================
    # 3. LIFECYCLE EVENTS (full chain: generated -> deployed)
    # =========================================================================
    print("\n[SEED] Creating lifecycle events...")

    lifecycle_stages = [
        ("generated",      "IdeatorAgent",   "Strategy generated by IdeatorAgent under regime mean_reversion_equity"),
        ("coding",         "CoderAgent",     "Strategy code written and syntax validated"),
        ("backtesting",    "BacktestRunner",  "Backtest completed: Sharpe=1.85, WinRate=67%, Trades=142"),
        ("validating",     "ValidatorAgent",  "Walk-forward: PASS | Monte Carlo: PASS | Overfitting: LOW (12%)"),
        ("promoting",      "DeploymentGovernor", "Composite fitness=0.72, approved for paper deployment"),
        ("deploying",      "ExecutionGateway",   "Strategy deployed to paper_trading mode"),
    ]

    stage_time = now - timedelta(hours=48)
    for stage, actor, meta_desc in lifecycle_stages:
        event_id = str(uuid.uuid4())
        metadata = '{"description": "' + meta_desc + '", "timestamp": "' + stage_time.isoformat() + '"}'
        await conn.execute("""
            INSERT INTO lifecycle_events (id, trace_id, strategy_id, stage, status, actor, metadata, created_at)
            VALUES ($1, $2, $3, $4, 'completed', $5, $6::jsonb, $7)
        """, event_id, TRACE_ID, STRATEGY_ID, stage, actor, metadata, stage_time)
        stage_time += timedelta(hours=1)

    print(f"  [OK] 6 lifecycle events: generated -> coding -> backtesting -> validating -> promoting -> deploying")

    # =========================================================================
    # 4. OPEN POSITION (AAPL buy @ $100, current market @ $105, unrealized +$50)
    # =========================================================================
    print("\n[SEED] Creating open position...")

    open_pos_id = str(uuid.uuid4())
    open_time = now - timedelta(hours=2)

    await conn.execute("""
        INSERT INTO positions (id, strategy_id, account_ref, symbol, side, qty, avg_price, broker,
                               unrealized_pnl, realized_pnl, trace_id, last_mark_time, created_at, updated_at)
        VALUES ($1, $2, 'demo_account', 'AAPL', 'buy', 10, 100.0, 'simulator',
                50.0, 0.0, $3, $4, $5, $5)
    """, open_pos_id, STRATEGY_ID, TRACE_ID, now, open_time)

    # Market data to support the current price ($105)
    for hours_ago in [2, 1, 0]:
        tick_time = now - timedelta(hours=hours_ago)
        close_px = 100.0 if hours_ago == 2 else 103.0 if hours_ago == 1 else 105.0
        await conn.execute("""
            INSERT INTO market_data_l1 (time, symbol, open, high, low, close, volume, source, interval, asset_class)
            VALUES ($1, 'AAPL', $2, $3, $4, $5, 8500000, 'polygon', '1m', 'equity')
        """, tick_time, close_px - 0.5, close_px + 0.8, close_px - 0.3, close_px)

    print("  [OK] Open position: AAPL buy 10 @ $100, current @ $105 (unrealized PnL: +$50.00)")

    # =========================================================================
    # 5. CLOSED TRADE (completed buy->sell cycle, realized PnL = +$110)
    # =========================================================================
    print("\n[SEED] Creating closed trade...")

    close_time = now - timedelta(minutes=30)
    entry_price = 100.0
    exit_price = 111.0
    qty = 10
    realized_pnl = qty * (exit_price - entry_price) if side == "sell" else qty * (entry_price - exit_price)

    # Buy leg
    await conn.execute("""
        INSERT INTO paper_trades (time, strategy_id, symbol, side, quantity, price, fill_price, status, pnl)
        VALUES ($1, $2::uuid, 'AAPL', 'buy', $3, $4, $4, 'filled', 0.0)
    """, close_time - timedelta(minutes=5), STRATEGY_ID, qty, entry_price)

    # Sell leg
    await conn.execute("""
        INSERT INTO paper_trades (time, strategy_id, symbol, side, quantity, price, fill_price, status, pnl)
        VALUES ($1, $2::uuid, 'AAPL', 'sell', $3, $4, $4, 'filled', $5)
    """, close_time, STRATEGY_ID, qty, exit_price, realized_pnl)

    # Market data for the exit price
    await conn.execute("""
        INSERT INTO market_data_l1 (time, symbol, open, high, low, close, volume, source, interval, asset_class)
        VALUES ($1, 'AAPL', 110.5, 111.8, 109.9, 111.0, 9200000, 'polygon', '1m', 'equity')
    """, close_time)

    print(f"  [OK] Closed trade: AAPL buy @ $100 -> sell @ $111 (realized PnL: +${realized_pnl:.2f})")

    # =========================================================================
    # SUMMARY
    # =========================================================================
    print("\n" + "=" * 60)
    print("DEMO DATA SEEDED SUCCESSFULLY")
    print("=" * 60)

    # Verify counts
    s_count = await conn.fetchval("SELECT COUNT(*) FROM strategies")
    l_count = await conn.fetchval("SELECT COUNT(*) FROM lifecycle_events")
    p_count = await conn.fetchval("SELECT COUNT(*) FROM positions")
    t_count = await conn.fetchval("SELECT COUNT(*) FROM paper_trades")
    b_count = await conn.fetchval("SELECT COUNT(*) FROM backtest_results")
    m_count = await conn.fetchval("SELECT COUNT(*) FROM market_data_l1 WHERE symbol = 'AAPL'")
    print(f"\n  Strategies:       {s_count}")
    print(f"  Lifecycle events: {l_count}")
    print(f"  Open positions:   {p_count}")
    print(f"  Paper trades:     {t_count}")
    print(f"  Backtest results: {b_count}")
    print(f"  AAPL market bars: {m_count}")


async def run():
    conn = await asyncpg.connect(DB_URL)
    try:
        await seed(conn)
    finally:
        await conn.close()

if __name__ == "__main__":
    asyncio.run(run())
