"""
Strategy Normalizer — translates Claude's creative strategy specs
into ATLAS executable schema.

Pipeline:
Claude → normalize → validate → compile-safe codegen
"""

import hashlib
import re
from typing import Any

# =====================================================
# FEATURE REGISTRY
# =====================================================
SUPPORTED_FEATURES = {
    "returns",
    "log_returns",
    "rsi_14",
    "macd",
    "macd_signal",
    "sma_5",
    "sma_20",
    "ema_12",
    "ema_26",
    "vwap",
    "bollinger_upper",
    "bollinger_lower",
    "rolling_volatility",
    # New normalized cross-asset features
    "price_vs_vwap_pct",
    "ema_spread_pct",
    "relative_volume",
    "bollinger_band_position",
    "volatility_regime",
    "trend_strength",
}

ALSO_ALLOWED = {
    "close",
    "open",
    "high",
    "low",
    "volume",
}

KNOWN_FEATURES = SUPPORTED_FEATURES | ALSO_ALLOWED

MAX_CONDITIONS = 4

# Longest first prevents macd/macd_signal overlap
_FEATURE_PATTERN = re.compile(
    r"\b("
    + "|".join(re.escape(f) for f in sorted(KNOWN_FEATURES, key=len, reverse=True))
    + r")\b"
)

# Matches numeric literals with 7+ decimal places (Claude overprecision)
_OVERPRECISE_NUM = re.compile(r"\b(\d+\.\d{7,})\b")
# Matches raw price-level comparisons: close > 700, open < 1000, etc.
_RAW_PRICE_PAT = re.compile(r"\b(close|open|high|low)\b\s*[<>]=?\s*(\d+(?:\.\d+)?)")


# =====================================================
# THRESHOLD NORMALIZATION
# =====================================================
def _normalize_thresholds(expr: str) -> str:
    """Auto-round overprecise numeric literals generated by Claude.

    Examples:
        returns > 0.000193847281  →  returns > 0.000194
        rsi_14 < 29.999999        →  rsi_14 < 30.0
    """

    def _rounder(m: re.Match) -> str:
        val = float(m.group(1))
        # Very small numbers (returns/log_returns range) → keep 8dp
        if abs(val) < 0.01:
            return str(round(val, 8))
        # Mid-range values (indicators, ratios) → 6dp
        if abs(val) < 100:
            return str(round(val, 6))
        # Large values (price-like) → 4dp
        return str(round(val, 4))

    return _OVERPRECISE_NUM.sub(_rounder, expr)


def _has_raw_price_threshold(expr: str) -> bool:
    """Detect hard-coded absolute price conditions like 'close > 700'.

    These are meaningless as universal thresholds — strategies using them
    would only work on one symbol at one price level.
    """
    for m in _RAW_PRICE_PAT.finditer(expr):
        try:
            threshold = float(m.group(2))
            if threshold > 10.0:  # $10 is a reasonable cutoff
                return True
        except ValueError:
            pass
    return False


# =====================================================
# BASIC HELPERS
# =====================================================
def _known_features_in(text: str) -> set:
    return {m.group(1) for m in _FEATURE_PATTERN.finditer(text)}


# Feature -> precision map for threshold rounding
_FEATURE_PRECISION: dict[str, int] = {
    "rsi_14": 0,
    "returns": 4,
    "log_returns": 4,
    "volume": 0,
    "close": 4,
    "open": 4,
    "high": 4,
    "low": 4,
    "vwap": 4,
    "bollinger_upper": 4,
    "bollinger_lower": 4,
    "sma_5": 4,
    "sma_20": 4,
    "ema_12": 6,
    "ema_26": 6,
    "macd": 6,
    "macd_signal": 6,
    "rolling_volatility": 6,
}


def _precision_for_condition(condition: str) -> int:
    best = 6
    for feat, prec in _FEATURE_PRECISION.items():
        if feat in condition:
            if prec < best:
                best = prec
    return best


# Pattern matches: optional whitespace, a comparison threshold value (number)
_THRESHOLD_VALUE_PATTERN = re.compile(r"(\s*[><=!]+\s*)(-?\d+\.?\d*)")


def normalize_thresholds(conditions: list[str]) -> list[str]:
    out = []
    for cond in conditions:
        precision = _precision_for_condition(cond)

        def _replacer(m: re.Match) -> str:
            prefix = m.group(1)
            raw = m.group(2)
            try:
                rounded = round(float(raw), precision)
                if precision == 0:
                    return f"{prefix}{int(rounded)}"
                return f"{prefix}{rounded}"
            except (ValueError, TypeError):
                return m.group(0)

        out.append(_THRESHOLD_VALUE_PATTERN.sub(_replacer, cond))
    return out


def _is_pure_boolean_expr(expr: str) -> bool:
    if not any(op in expr for op in (">=", "<=", "!=", "==", ">", "<")):
        return False

    REJECT_WORDS = [
        "for",
        "current",
        "candle",
        "breaks",
        "crosses",
        "above",
        "below",
        "when",
        "if",
        "same",
        "preceding",
        "immediately",
        "entry",
        "condition",
    ]
    lower = expr.lower()
    for word in REJECT_WORDS:
        if re.search(r"\b" + re.escape(word) + r"\b", lower):
            return False

    test_expr = _FEATURE_PATTERN.sub("X", expr)
    test_expr = re.sub(r"[X\d\s\.\+\-\*\/\>\<\=\!\&\|\(\)\,]", "", test_expr)
    if test_expr.strip():
        return False

    return True


def _replace_feature(match: re.Match) -> str:
    return f"df['{match.group(1)}']"


# =====================================================
# CONDITION NORMALIZATION
# =====================================================
def normalize_conditions(conditions: list) -> list:
    out = []
    for condition in conditions:
        if not isinstance(condition, str):
            continue
        condition = condition.strip()
        if not condition:
            continue
        if len(condition) > 120:
            continue
        if not _known_features_in(condition):
            continue
        # Auto-round overprecise numeric thresholds
        condition = _normalize_thresholds(condition)
        # Reject raw absolute price thresholds (close > 700 etc.)
        if _has_raw_price_threshold(condition):
            continue
        out.append(condition)
    return out[:MAX_CONDITIONS]


# =====================================================
# STRATEGY NORMALIZATION
# =====================================================
def normalize_strategy(spec: dict) -> dict:
    out = dict(spec)

    out["entry_conditions"] = normalize_conditions(spec.get("entry_conditions", []))

    out["exit_conditions"] = normalize_conditions(spec.get("exit_conditions", []))

    # Safe defaults
    out.setdefault("strategy_name", "Unknown")
    out.setdefault("hypothesis", "")
    out.setdefault("stop_loss", "2% below entry")
    out.setdefault("take_profit", "5% above entry")
    out.setdefault("position_sizing", "10% of portfolio")
    out.setdefault("timeframe", "5m")
    out.setdefault("asset_class", "crypto")
    out.setdefault("expected_sharpe", 1.0)
    out.setdefault("expected_win_rate", 0.5)
    out.setdefault("risk_level", "medium")
    out.setdefault("tags", [])

    return out


# =====================================================
# DIVERSITY SCORING
# =====================================================
_FEATURE_FAMILIES: dict[str, str] = {
    "rsi_14": "oscillator",
    "macd": "oscillator",
    "macd_signal": "oscillator",
    "sma_5": "trend",
    "sma_20": "trend",
    "ema_12": "trend",
    "ema_26": "trend",
    "bollinger_upper": "volatility",
    "bollinger_lower": "volatility",
    "bollinger_band_position": "volatility",
    "rolling_volatility": "volatility",
    "volatility_regime": "volatility",
    "vwap": "volume",
    "price_vs_vwap_pct": "volume",
    "relative_volume": "volume",
    "returns": "momentum",
    "log_returns": "momentum",
    "trend_strength": "trend",
    "ema_spread_pct": "trend",
    "close": "price",
    "open": "price",
    "high": "price",
    "low": "price",
    "volume": "volume",
}


def _families_used(conditions: list[str]) -> set[str]:
    families: set[str] = set()
    for cond in conditions:
        for feat, family in _FEATURE_FAMILIES.items():
            if feat in cond:
                families.add(family)
    return families


def compute_diversity_score(entry: list[str], exit_: list[str]) -> float:
    """
    Score [0.0, 1.0] how feature-diverse a strategy is.
    1.0 = uses 3+ distinct families → desirable
    0.0 = only 1 family (e.g. only EMA/RSI clones) → penalized
    """
    all_conds = entry + exit_
    if not all_conds:
        return 0.0
    families = _families_used(all_conds)
    n = len(families)
    if n >= 3:
        return 1.0
    if n == 2:
        return 0.6
    return 0.0


def _is_clone(entry: list[str], exit_: list[str]) -> bool:
    """Detect EMA/RSI-only strategies with no additional factors."""
    families = _families_used(entry + exit_)
    return families <= {"oscillator", "trend"} and len(families) <= 2


# =====================================================
# STRATEGY SIGNATURE
# =====================================================
def compute_strategy_signature(spec: dict) -> str:
    entry = sorted(spec.get("entry_conditions", []))
    exit_ = sorted(spec.get("exit_conditions", []))
    asset = spec.get("asset_class", "unknown")
    raw = str(entry) + str(exit_) + asset
    return hashlib.md5(raw.encode()).hexdigest()


# =====================================================
# VALIDATION
# =====================================================
def validate_strategy(spec: dict) -> tuple[bool, str]:
    entry = spec.get("entry_conditions", [])
    exit_ = spec.get("exit_conditions", [])

    if not entry and not exit_:
        return False, "No entry or exit conditions after normalization"

    if (
        not isinstance(spec.get("strategy_name"), str)
        or not spec["strategy_name"].strip()
    ):
        return False, "Missing strategy_name"

    total_conds = len(entry) + len(exit_)
    if total_conds < 2:
        return False, f"Too few conditions ({total_conds}); need at least 2"

    if _is_clone(entry, exit_):
        return False, "Rejected as EMA/RSI-only clone with no additional factors"

    return True, "ok"


# =====================================================
# COMPILATION
# =====================================================
def _compile_condition(expr: str) -> str | None:
    if not _is_pure_boolean_expr(expr):
        return None

    expr = expr.strip()
    compiled = _FEATURE_PATTERN.sub(_replace_feature, expr)

    test = compiled.replace("df['", "x.").replace("']", "")
    try:
        compile(f"result = {test}", "<test>", "exec")
    except SyntaxError:
        return None

    return f"({compiled})"


# =====================================================
# CODE GENERATION
# =====================================================
def conditions_to_code(entry_conditions: list, exit_conditions: list) -> str:
    """
    Returns a block indented for insertion inside generate_signals()
    at 8-space (2-level) indentation.

    Output example:
        entry = (
            (df['rsi_14'] < 30)
            & (df['macd'] > df['macd_signal'])
        )

        exit_ = (
            (df['rsi_14'] > 70)
        )
    """

    def build_series_expr(conditions: list, operator: str) -> str:
        compiled = []
        for cond in conditions:
            result = _compile_condition(cond)
            if result:
                compiled.append(result)

        if not compiled:
            return "pd.Series(False, index=df.index)"
        if len(compiled) == 1:
            return compiled[0]

        inner = f"\n            {operator} ".join(compiled)
        return f"(\n            {inner}\n        )"

    entry_expr = build_series_expr(entry_conditions, "&")
    exit_expr = build_series_expr(exit_conditions, "|")

    # 8-space indent = 2 levels deep inside generate_signals()
    # Use exit_ not exit (exit is a Python builtin, causes SyntaxError)
    block = f"        entry = {entry_expr}\n\n        exit_ = {exit_expr}"
    return block
